all:
	gcc multicast_nl_send_3.c -o send3
	gcc multicast_nl_send_5.c -o send5
	gcc multicast_nl_send_3_5.c -o send35
	gcc multicast_nl_recv_3.c -o recv3
	gcc multicast_nl_recv_5.c -o recv5
	gcc multicast_nl_recv_3_5.c -o recv35

clean:
	rm send* recv*
